spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    # Producer 설정
    producer:
      # At Least Once 보장을 위한 설정
      acks: all # 모든 ISR replica가 메시지를 받을 때까지 대기
      retries: 3 # 실패 시 재시도 횟수
      # 멱등성 보장
      properties:
        enable.idempotence: true # 멱등 프로듀서 활성화 (중복 메시지 방지)
        max.in.flight.requests.per.connection: 5 # 멱등성 보장하면서 허용되는 최대 in-flight 요청 수
      # 직렬화
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 배치 설정 (성능 최적화)
      batch-size: 16384 # 16KB
      linger-ms: 10 # 10ms 대기 후 배치 전송
      compression-type: snappy # 압축 타입

    # Consumer 설정
    consumer:
      # Consumer Group 설정
      group-id: commerce-consumer-group
      # 수동 커밋 (멱등성 보장)
      enable-auto-commit: false # 수동 Ack
      # Offset 리셋 정책
      auto-offset-reset: earliest # 처음부터 읽기
      # 역직렬화
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # JSON 역직렬화 설정
        spring.json.trusted.packages: "*"
        # 세션 타임아웃
        session.timeout.ms: 30000 # 30초
        # 하트비트 간격
        heartbeat.interval.ms: 10000 # 10초
        # 최대 poll 간격 (이 시간 내에 poll을 호출해야 함)
        max.poll.interval.ms: 300000 # 5분
        # 한 번에 가져올 최대 레코드 수
        max.poll.records: 10

    # Listener 설정
    listener:
      # 수동 Ack 모드
      ack-mode: manual
      # 동시성 (파티션 수에 맞춰 조정)
      concurrency: 3
      # 에러 핸들링
      type: batch # 배치 리스너 사용

# Kafka Topic 설정
kafka:
  topics:
    catalog-events: catalog-events
    order-events: order-events
    catalog-events-dlq: catalog-events-dlq
    order-events-dlq: order-events-dlq

  # Outbox Relay 설정
  outbox:
    relay:
      enabled: true
      fixed-delay: 5000 # 5초마다 실행
      initial-delay: 10000 # 시작 10초 후 첫 실행
      batch-size: 100 # 한 번에 처리할 최대 이벤트 수
      max-retry-count: 3 # 최대 재시도 횟수

---
spring:
  config:
    activate:
      on-profile: local

kafka:
  outbox:
    relay:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  kafka:
    # Docker Compose Kafka 사용 (docker/infra-compose.yml)
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

kafka:
  outbox:
    relay:
      # 테스트 환경에서는 스케줄러 비활성화 (수동으로 테스트)
      enabled: false

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd
